/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_swordsman_inaction_share_ffmpegforandroid_FFMpegLib */

#ifndef _Included_com_swordsman_inaction_share_ffmpegforandroid_FFMpegLib
#define _Included_com_swordsman_inaction_share_ffmpegforandroid_FFMpegLib

/*
 * Class:     com_swordsman_inaction_share_ffmpegforandroid_FFMpegLib
 * Method:    nativeFFMpeg
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_swordsman_1inaction_share_ffmpegforandroid_FFMpegLib_nativeFFMpeg
  (JNIEnv *, jclass, jstring);


#endif
